services:
  - type: web
    name: sorbazaar-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES
        value: "7d"
      - key: PORT
        value: "10000"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "https://tansoura.in"
      - key: NODE_ENV
        value: "production"